[2021-10-14 00:00:01,818] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 00:00:01,827] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 00:00:01,827] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 00:00:01,827] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-14 00:00:01,827] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 00:00:01,839] {taskinstance.py:1262} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-10-13 00:00:00+00:00
[2021-10-14 00:00:01,843] {standard_task_runner.py:52} INFO - Started process 5594 to run task
[2021-10-14 00:00:01,846] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2021-10-13T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0_s_ytj7', '--error-file', '/tmp/tmpezko1g6p']
[2021-10-14 00:00:01,846] {standard_task_runner.py:77} INFO - Job 20: Subtask is_api_available
[2021-10-14 00:00:01,876] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2021-10-13T00:00:00+00:00 [running]> on host 981af2cc3d86
[2021-10-14 00:00:01,921] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 00:00:01,921] {http.py:101} INFO - Poking: api/
[2021-10-14 00:00:01,947] {base.py:79} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-14 00:00:01,950] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-10-14 00:00:02,222] {base.py:249} INFO - Success criteria met. Exiting.
[2021-10-14 00:00:02,232] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211013T000000, start_date=20211014T000001, end_date=20211014T000002
[2021-10-14 00:00:02,262] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 00:00:02,300] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-14 00:00:22,207] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T00:00:19.776851+00:00 [queued]>
[2021-10-14 00:00:22,224] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T00:00:19.776851+00:00 [queued]>
[2021-10-14 00:00:22,224] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 00:00:22,224] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-14 00:00:22,224] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 00:00:22,242] {taskinstance.py:1262} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-10-14 00:00:19.776851+00:00
[2021-10-14 00:00:22,246] {standard_task_runner.py:52} INFO - Started process 5628 to run task
[2021-10-14 00:00:22,248] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2021-10-14T00:00:19.776851+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8bo0frl6', '--error-file', '/tmp/tmp4hiz1v22']
[2021-10-14 00:00:22,248] {standard_task_runner.py:77} INFO - Job 25: Subtask is_api_available
[2021-10-14 00:00:22,295] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.is_api_available manual__2021-10-14T00:00:19.776851+00:00 [running]> on host 981af2cc3d86
[2021-10-14 00:00:22,335] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T00:00:19.776851+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T00:00:19.776851+00:00
[2021-10-14 00:00:22,336] {http.py:101} INFO - Poking: api/
[2021-10-14 00:00:22,344] {base.py:79} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-14 00:00:22,347] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-10-14 00:00:22,546] {base.py:249} INFO - Success criteria met. Exiting.
[2021-10-14 00:00:22,559] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211014T000019, start_date=20211014T000022, end_date=20211014T000022
[2021-10-14 00:00:22,587] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 00:00:22,622] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-14 19:09:01,704] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [queued]>
[2021-10-14 19:09:01,719] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [queued]>
[2021-10-14 19:09:01,719] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:09:01,719] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-14 19:09:01,719] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:09:01,729] {taskinstance.py:1262} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-10-14 19:08:59.171717+00:00
[2021-10-14 19:09:01,733] {standard_task_runner.py:52} INFO - Started process 139 to run task
[2021-10-14 19:09:01,736] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2021-10-14T19:08:59.171717+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpp6hirfwm', '--error-file', '/tmp/tmp_w7qfvqr']
[2021-10-14 19:09:01,736] {standard_task_runner.py:77} INFO - Job 34: Subtask is_api_available
[2021-10-14 19:09:01,766] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [running]> on host 981af2cc3d86
[2021-10-14 19:09:01,804] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T19:08:59.171717+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T19:08:59.171717+00:00
[2021-10-14 19:09:01,804] {http.py:101} INFO - Poking: api/
[2021-10-14 19:09:01,811] {base.py:79} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-14 19:09:01,813] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-10-14 19:09:02,182] {base.py:249} INFO - Success criteria met. Exiting.
[2021-10-14 19:09:02,192] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211014T190859, start_date=20211014T190901, end_date=20211014T190902
[2021-10-14 19:09:02,231] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 19:09:02,272] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
