[2021-10-14 19:45:58,642] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 19:45:58,656] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 19:45:58,656] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:45:58,656] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-14 19:45:58,656] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:45:58,667] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-10-13 00:00:00+00:00
[2021-10-14 19:45:58,672] {standard_task_runner.py:52} INFO - Started process 1130 to run task
[2021-10-14 19:45:58,680] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2021-10-13T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', '/home/***/.local/lib/python3.6/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp60fl9wn6', '--error-file', '/tmp/tmp9mp8whzv']
[2021-10-14 19:45:58,680] {standard_task_runner.py:77} INFO - Job 51: Subtask run_after_loop
[2021-10-14 19:45:58,736] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2021-10-13T00:00:00+00:00 [running]> on host 981af2cc3d86
[2021-10-14 19:45:58,773] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 19:45:58,774] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-14 19:45:58,774] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2021-10-14 19:45:58,781] {subprocess.py:85} INFO - Output:
[2021-10-14 19:45:58,782] {subprocess.py:89} INFO - 1
[2021-10-14 19:45:58,782] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-14 19:45:58,802] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20211013T000000, start_date=20211014T194558, end_date=20211014T194558
[2021-10-14 19:45:58,848] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 19:45:58,877] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 19:46:02,865] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2021-10-14T19:45:59.165912+00:00 [queued]>
[2021-10-14 19:46:02,879] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2021-10-14T19:45:59.165912+00:00 [queued]>
[2021-10-14 19:46:02,880] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:46:02,880] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-14 19:46:02,880] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:46:02,889] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-10-14 19:45:59.165912+00:00
[2021-10-14 19:46:02,895] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2021-10-14T19:45:59.165912+00:00', '--job-id', '57', '--raw', '--subdir', '/home/***/.local/lib/python3.6/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpin_rhi8l', '--error-file', '/tmp/tmpqocatq_t']
[2021-10-14 19:46:02,896] {standard_task_runner.py:77} INFO - Job 57: Subtask run_after_loop
[2021-10-14 19:46:02,893] {standard_task_runner.py:52} INFO - Started process 1148 to run task
[2021-10-14 19:46:02,927] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2021-10-14T19:45:59.165912+00:00 [running]> on host 981af2cc3d86
[2021-10-14 19:46:02,966] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T19:45:59.165912+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T19:45:59.165912+00:00
[2021-10-14 19:46:02,967] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-14 19:46:02,967] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2021-10-14 19:46:02,975] {subprocess.py:85} INFO - Output:
[2021-10-14 19:46:02,976] {subprocess.py:89} INFO - 1
[2021-10-14 19:46:02,977] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-14 19:46:02,997] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20211014T194559, start_date=20211014T194602, end_date=20211014T194602
[2021-10-14 19:46:03,029] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 19:46:03,071] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
